import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Tab from './components/Tab';
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-black text-green-400 py-4 px-8 border-b-2 border-green-600">
        <div className="container mx-auto flex justify-center space-x-8">
        <Link href="/chickens">  <Tab label="Курицы"  /> </Link>
        <Link href="/cages">   <Tab label="Клетки"  /></Link>
      <Link href="/workers">  <Tab label="Работники"  /></Link>
        </div>
      </header>

        {children}
      </body>
    </html>
  );
}
